version: "3.7"

services:
  nginx:
    image: nginx:1.14.0-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  front:
    image: edurossi82/node:1.0.1
    restart: unless-stopped
    volumes:
      - ../front:/app
    working_dir: /app
    command: npm run start

  back:
    image: edurossi82/node:1.0.1
    restart: unless-stopped
    volumes:
      - ../back:/app
    working_dir: /app
    command: npm run start

  mongo:
    image: mongo:4.1.13
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
